# Machine learning

This notebook investigates whether impedance measurements can be used to distinguish between intact and fractured bone measurements from the four hammer tests.

The data are grouped into:
- No fracture hammer 1–4
- 100% fracture hammer 1–4

The analysis includes:
- Loading and grouping the impedance measurements
- Outlier detection using a z-score threshold
- Calculating the impedance change between intact and fractured measurements for each hammer test
- Training a logistic regression classifier
- Evaluating the classifier using 5-fold stratified cross-validation
- Comparing classification with and without PCA
- Evaluating a separate train/test split using measurements from different hammer tests
- Generating a confusion matrix and classification report

The machine-learning analysis is used to investigate whether the impedance spectra contain sufficient information to distinguish between intact and fractured measurements.

### Imports

In [1]:
# Import packages
from pathlib import Path
import pandas as pd
import numpy as np

from scipy.stats import zscore
from sklearn.decomposition import PCA
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [2]:
FOLDERS = {
    "../data/03_hammer_tests/test_01/00_intact": "No fracture hammer 1",
    "../data/03_hammer_tests/test_01/100_fractured": "100% Fracture hammer 1",
    "../data/03_hammer_tests/test_02/00_intact": "No fracture hammer 2",
    "../data/03_hammer_tests/test_02/100_fractured": "100% Fracture hammer 2",
    "../data/03_hammer_tests/test_03/00_intact": "No fracture hammer 3",
    "../data/03_hammer_tests/test_03/100_fractured": "100% Fracture hammer 3",
    "../data/03_hammer_tests/test_04/00_intact": "No fracture hammer 4",
    "../data/03_hammer_tests/test_04/100_fractured": "100% Fracture hammer 4"
}

group_data = {}

for folder, label in FOLDERS.items():

    csv_files = sorted(Path(folder).glob("*.csv"))

    if not csv_files:
        print(f"No CSV files found in {folder}")
        continue

    impedances = []
    frequency = None

    for csv_file in csv_files:

        df = pd.read_csv(csv_file)

        if frequency is None:
            frequency = df["frequency"].values

        # Skip incomplete sweeps
        if len(df) != len(frequency):
            print(
                f"Skipping {csv_file.name}: "
                f"{len(df)} rows instead of {len(frequency)}"
            )
            continue

        impedances.append(df["impedance"].values)

    if len(impedances) == 0:
        print(f"No valid files found in {folder}")
        continue

    impedances = np.vstack(impedances)

    group_data[label] = {
        "frequency": frequency,
        "mean": np.mean(impedances, axis=0),
        "std": np.std(impedances, axis=0),
        "raw": impedances,
        "n": len(csv_files)
    }

    print(f"{label}: {len(impedances)} files loaded")

No fracture hammer 1: 6 files loaded
100% Fracture hammer 1: 15 files loaded
No fracture hammer 2: 11 files loaded
100% Fracture hammer 2: 14 files loaded
No fracture hammer 3: 7 files loaded
100% Fracture hammer 3: 7 files loaded
No fracture hammer 4: 9 files loaded
100% Fracture hammer 4: 9 files loaded

### Outlier detection

In [3]:
print("OUTLIER REPORT")
print("=" * 40)

for group_name, data in group_data.items():

    sweep_means = np.mean(
        data["raw"],
        axis=1
    )

    z_scores = np.abs(
        zscore(sweep_means)
    )

    outliers = np.where(
        z_scores > 2.5
    )[0]

    print(f"\n{group_name}")

    if len(outliers) == 0:
        print("No outliers found")

    else:
        print(f"Outliers: {outliers}")

OUTLIER REPORT
========================================

No fracture hammer 1
No outliers found

100% Fracture hammer 1
No outliers found

No fracture hammer 2
Outliers: [3]

100% Fracture hammer 2
Outliers: [9]

No fracture hammer 3
No outliers found

100% Fracture hammer 3
No outliers found

No fracture hammer 4
Outliers: [0]

100% Fracture hammer 4
No outliers found

In [4]:
import pandas as pd
import numpy as np
from itertools import combinations

rows = []

for hammer in [1, 2, 3, 4]:

    intact_key = f"No fracture hammer {hammer}"
    fracture_key = f"100% Fracture hammer {hammer}"

    intact_sweeps = group_data[intact_key]["raw"]
    fracture_sweeps = group_data[fracture_key]["raw"]

    # Frequency values for this hammer test
    freq = group_data[intact_key]["frequency"]

    # Fracture examples
    for intact in intact_sweeps:
        for fractured in fracture_sweeps:

            relative_change = (
                fractured - intact
            ) / intact

            row = dict(zip(freq, relative_change))
            row["broken"] = True
            row["hammer"] = hammer

            rows.append(row)

    # Non-fracture examples
    for intact1, intact2 in combinations(intact_sweeps, 2):

        relative_change = (
            intact2 - intact1
        ) / intact1

        row = dict(zip(freq, relative_change))
        row["broken"] = False
        row["hammer"] = hammer

        rows.append(row)


df_changes = pd.DataFrame(rows)

print(df_changes.shape)
display(df_changes.head())

(501, 53)

,10000.0,11800.0,13600.0,15400.0,17200.0,19000.0,20800.0,22600.0,24400.0,26200.0,...,87400.0,89200.0,91000.0,92800.0,94600.0,96400.0,98200.0,100000.0,broken,hammer
0,-0.167865,-0.171328,-0.166593,-0.167370,-0.166183,-0.169603,-0.164074,-0.167631,-0.162304,-0.163794,...,-0.140804,-0.137477,-0.138711,-0.138827,-0.137818,-0.138193,-0.136126,-0.136395,True,1
1,-0.170384,-0.171181,-0.159095,-0.163356,-0.158369,-0.162127,-0.159384,-0.161693,-0.162154,-0.158686,...,-0.138763,-0.137496,-0.137686,-0.137270,-0.135927,-0.136915,-0.135100,-0.134157,True,1
2,-0.151840,-0.160090,-0.159316,-0.161238,-0.165564,-0.164514,-0.157508,-0.164990,-0.159814,-0.160301,...,-0.140471,-0.139378,-0.137844,-0.138137,-0.137640,-0.137780,-0.135830,-0.136120,True,1
3,-0.147912,-0.171603,-0.163001,-0.167797,-0.160299,-0.163478,-0.160416,-0.164616,-0.158222,-0.160827,...,-0.138802,-0.137555,-0.136622,-0.138176,-0.135848,-0.136207,-0.134588,-0.134294,True,1
4,-0.164456,-0.162826,-0.150879,-0.158433,-0.154191,-0.162442,-0.160172,-0.160850,-0.156649,-0.158499,...,-0.137408,-0.134065,-0.135618,-0.135712,-0.133977,-0.134320,-0.133602,-0.132331,True,1

In [5]:
df_changes

,10000.0,11800.0,13600.0,15400.0,17200.0,19000.0,20800.0,22600.0,24400.0,26200.0,...,87400.0,89200.0,91000.0,92800.0,94600.0,96400.0,98200.0,100000.0,broken,hammer
0,-0.167865,-0.171328,-0.166593,-0.167370,-0.166183,-0.169603,-0.164074,-0.167631,-0.162304,-0.163794,...,-0.140804,-0.137477,-0.138711,-0.138827,-0.137818,-0.138193,-0.136126,-0.136395,True,1
1,-0.170384,-0.171181,-0.159095,-0.163356,-0.158369,-0.162127,-0.159384,-0.161693,-0.162154,-0.158686,...,-0.138763,-0.137496,-0.137686,-0.137270,-0.135927,-0.136915,-0.135100,-0.134157,True,1
2,-0.151840,-0.160090,-0.159316,-0.161238,-0.165564,-0.164514,-0.157508,-0.164990,-0.159814,-0.160301,...,-0.140471,-0.139378,-0.137844,-0.138137,-0.137640,-0.137780,-0.135830,-0.136120,True,1
3,-0.147912,-0.171603,-0.163001,-0.167797,-0.160299,-0.163478,-0.160416,-0.164616,-0.158222,-0.160827,...,-0.138802,-0.137555,-0.136622,-0.138176,-0.135848,-0.136207,-0.134588,-0.134294,True,1
4,-0.164456,-0.162826,-0.150879,-0.158433,-0.154191,-0.162442,-0.160172,-0.160850,-0.156649,-0.158499,...,-0.137408,-0.134065,-0.135618,-0.135712,-0.133977,-0.134320,-0.133602,-0.132331,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,-0.004726,0.017782,0.019598,0.003412,0.002280,-0.001038,0.014468,0.005379,0.004589,-0.001050,...,-0.001860,-0.000304,0.001268,0.000193,-0.001252,-0.000752,-0.002041,0.000756,False,4
497,-0.010599,0.006957,0.007995,0.001045,-0.004450,-0.006490,-0.005817,0.004399,0.001668,-0.002101,...,-0.000590,-0.000575,-0.000396,0.000386,-0.000512,0.000490,0.000757,0.000458,False,4
498,-0.011367,-0.003564,0.011511,0.005765,-0.002278,0.002558,0.007415,0.000187,-0.000384,0.000000,...,-0.001271,0.002112,-0.002144,0.000000,-0.001252,-0.000251,-0.001022,-0.000469,False,4
499,-0.017200,-0.014162,0.000000,0.003393,-0.008978,-0.002914,-0.012729,-0.000787,-0.003291,-0.001051,...,0.000000,0.001841,-0.003803,0.000193,-0.000512,0.000992,0.001779,-0.000766,False,4
500,-0.005900,-0.010636,-0.011380,-0.002359,-0.006715,-0.005458,-0.019995,-0.000975,-0.002908,-0.001051,...,0.001272,-0.000270,-0.001663,0.000193,0.000741,0.001243,0.002804,-0.000298,False,4

In [6]:
X = df_changes.drop(columns=["broken", "hammer"])
y = df_changes["broken"]

In [7]:
model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression())
])

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = cross_val_score(
    model,
    X,
    y,
    cv=cv,
    scoring="accuracy"
)

print("Fold accuracies:", scores)
print("Mean accuracy:", scores.mean())
print("Std:", scores.std())

Fold accuracies: [1.   0.92 0.94 0.98 0.96]
Mean accuracy: 0.96
Std: 0.028284271247461894

In [8]:
model = Pipeline([
    ("scaler", StandardScaler()),
    ("pca", PCA(n_components=0.95)),
    ("classifier", LogisticRegression())
])

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = cross_val_score(
    model,
    X,
    y,
    cv=cv,
    scoring="accuracy"
)

print("Fold accuracies:", scores)
print("Mean accuracy:", scores.mean())
print("Std:", scores.std())

Fold accuracies: [1.   0.91 0.92 0.93 0.94]
Mean accuracy: 0.9400000000000001
Std: 0.03162277660168378

In [9]:
print(group_data.keys())

first_key = list(group_data.keys())[0]

print(group_data[first_key].keys())

dict_keys(['No fracture hammer 1', '100% Fracture hammer 1', 'No fracture hammer 2', '100% Fracture hammer 2', 'No fracture hammer 3', '100% Fracture hammer 3', 'No fracture hammer 4', '100% Fracture hammer 4'])
dict_keys(['frequency', 'mean', 'std', 'raw', 'n'])

### test on 1-3, train on 4

In [10]:
train_df = df_changes[df_changes["hammer"].isin([1, 2, 3])]

test_df = df_changes[df_changes["hammer"] == 4]

X_train = train_df.drop(columns=["broken", "hammer"])
y_train = train_df["broken"]

X_test = test_df.drop(columns=["broken", "hammer"])
y_test = test_df["broken"]

In [11]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(max_iter=1000))
])

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.9316239316239316

Confusion Matrix:
[[28  8]
 [ 0 81]]

Classification Report:
              precision    recall  f1-score   support

       False       1.00      0.78      0.88        36
        True       0.91      1.00      0.95        81

    accuracy                           0.93       117
   macro avg       0.96      0.89      0.91       117
weighted avg       0.94      0.93      0.93       117

In [12]:
confusion_matrix(y_test, y_pred)

array([[28,  8],
       [ 0, 81]])